week8_assign_15/myblog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('blog/home');
//});

Route::get('/', 'PostController@publicHomePage');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('posts','PostController');

//Route::get('posts/indexsp', 'PostController@indexsp');
Route::get('posts/indexsp', [ 'uses' => 'PostController@indexsp', 'as' => 'posts.indexsp']); 

//Route::resource('comments','CommentController');
//Route::get('users/{id}', 'UserController@getProfile')->where('id', '[\d+]+');

Route::POST('comments/{post_id}', [ 'uses' => 'CommentController@store', 'as' => 'comments.store']); 

Route::POST('likes/{post_id}', [ 'uses' => 'LikeController@store', 'as' => 'likes.store']); 

Route::get('comments/{post_id}', [ 'uses' => 'CommentController@show', 'as' => 'comments.show']); 

week8_assign_15/myblog/resources/views/adminPanel/create.blade.php
@extends('layouts.template')

@section('title','')

@section('content')
<h1>Select</h1>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<div class="col-sm-8 col-sm-offset-2">


 <form action="{{ route('posts.store') }}"
enctype="multipart/form-data" method="post">
 {{ csrf_field() }}
 <hr>
<hr>
<p>
caption:<br>
<input type="text" name="textline" size="30">
</p>
<p>
<hr>
<hr>
select image:<br>
<input type="file" name="image" size="40" class="btn btn-primary pull-top">

</p>
<div>
<input type="submit" value="Attach" class="btn btn-primary pull-top" ><i class="material-icons" style="font-size:48px;color:red;">attachment</i></input>
</div>
</form>
</div>

@endsection

week8_assign_15/myblog/resources/views/adminPanel/edit.blade.php
@extends('layouts.template')

@section('title','Edit Post #' . $post->id)

@section('content')
<h1># {{ $post->id }}</h1>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<div class="col-sm-8 col-sm-offset-2">


  <form action="{{ route('comments.store', $post->id) }}" method="post">

 
  {{ csrf_field() }}


    
    <div class="form-group">

    </div>

    <div class="form-group">

      <textarea name="comment" class="form-control" cols="10" rows="10" required="required" style="height: 80px ;">
      </textarea>
    </div>




    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="../" class="btn btn-default pull-right">Go Back</a>
  </form>

<hr>


    <form action="{{ route('likes.store', $post->id) }}" method="post">

 
  {{ csrf_field() }}

    <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-thumbs-up" style="font-size:25px;color:red;"></i></button>

   
        <a href="#">
          <span class="glyphicon glyphicon-thumbs-down" style="font-size:15px;"></span>
        </a>
    
<hr>    

  </form>

      <form action="{{ route('comments.show', $post->id) }}" method="post">


  {{ csrf_field() }}
              <tbody>
          
      @foreach($post->comment as $comment1)
    <div class="alert alert-danger">

      <p>{{ $comment1->comment }}</p>
      <a href="{{ route('comments.show', ['id'=>$post->id]) }}" ></a>
     
    </div>
    @endforeach

        </tbody>


  </form>


</div>

@endsection

week8_assign_15/myblog/resources/views/adminPanel/home.blade.php
@extends('layouts.template')

@section('title','')

@section('content')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="loginBox nav navbar-nav pull-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> {{ Auth::user()->name }} <span class="caret"></span>
    </a>

    <ul class="dropdown-menu" role="menu">
      <li>
        <a href="logout" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>

        <form id="logout-form" action="logout" method="POST" style="display: none;"> {{ csrf_field() }}
        </form>
      </li>
    </ul>
  </li>
</div>

<hr>
<hr>
<a href="{{ url('/') }}" class="btn btn-primary pull-left"> <i class="fa fa-arrow-circle-o-left" style="font-size:36px"></i></a>

<a href="posts/create" class="btn btn-primary pull-right"> + </a>

<hr>
<hr>
<br><br><br>
<table class="table">

  <tbody>
    @foreach($posts as $post)
    <tr>
      <th>{{ $post-> id }}</th>

      <td>

        <div class="alert alert-info" align="center">{{ $post->caption }}</div>
      <img src="../../storage/app/{{ $post->image}}" border=3 height=400 width=300>
      
      </td>

      <td><a href="{{ route('posts.edit', ['id'=>$post->id]) }}" class="btn btn-info"><i class="fa fa-newspaper-o" style="font-size:36px"></i>

      </a>

      </td>
      
      <td>
      <form action="{{ route('posts.destroy', ['id'=>$post->id]) }}" method="post">
      {{ csrf_field() }}
        <input type="hidden" name="_method" value="DELETE">
        <i class="fa fa-trash"></i>
        <input class="btn btn-danger" type="submit" value="-">
      </form>
      </td>
    </tr>
    @endforeach
  </tbody>
</table>

@endsection