finalproject/webapp/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', 'TaskController@index');
Route::get('/calendar', 'TaskController@show');
Route::get('/list', 'SubtaskController@show');
Route::get('/listuser', 'SubtaskController@show');
Route::resource('/tasks', 'TaskController');
Route::resource('/subtasks', 'SubtaskController');

finalproject/webapp/app/Task.php
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
use App\Subtask;
use App\User;
class Task extends Model
{

    public function subtasks()
    {
        $result = $this->hasMany(Subtask::class, 'task_id')
        		->select(['id', 'subtask_name','user_id', 'subtask_due', 'updated_at', 'task_status'])
                ->groupby('id');
        		$array = $result;
        return $array;		
    }

	public function user()
    {
        return $this->belongsTo(User::class, 'id');
    }

}

finalproject/webapp/app/Http/Controllers/TaskController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Task;
use App\Subtask;
use App\User;
use Session;
use Auth;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use DB;
class TaskController extends Controller
{
    public function index()
    {    
        $loggedUserId = Auth::id();
        $users = DB::table('users')
                ->get()
                ->where('id', $loggedUserId);
            foreach ($users as $user)
            {
                $user->userstatus;
            }
        $task = new Task; 
            if ( $user->userstatus != 1) 
            {
                $tasks = Task::orderBy('id','task_name')
                        ->where('user_id', $loggedUserId)
                        ->paginate(3);
            }else{
                $tasks = Task::orderBy('id','task_name')
                        ->paginate(3);
            }
        $subtasks = DB::table('subtasks')
                    ->get()
                    ->where('user_id', $loggedUserId);
                    // exclude extra details from friends table
                    $data = DB::table("subtasks")
                    ->select(DB::raw("SUM(task_status) as sumt"))
                    ->groupBy(DB::raw("task_id"))
                    ->get();
        $value = json_decode($data, true);
            if ( $user->userstatus != 1) 
            {        
                return  
                    view('tasks.index') 
                    ->with('storedTasks', $tasks)
                    ->with('sumt', $data );
            }else{
                return  
                    view('tasks.admin') 
                    ->with('storedTasks', $tasks)
                    ->with('sumt', $data );
            }
    }
    public function create()
    {
        //
    }
    public function store(Request $request)
    {
        $this->validate($request, [
                'newTaskName' => 'required|min:5|max:255',
            ]);
        $data = $this->importCsv();
        for ($i = 0; $i < count($data); $i ++)
        {
            $task = new Task;
            $task->id =$data[$i]['id'];
            $task->task_name =$data[$i]['task_name'];
            $task->task_due ='2017-03-23 05:53:23';
            $task->task_status ='0';
            $task->user_id ='1';
            $task->save();
        }  
        Session::flash('success', 'New task has been succesfully added!');
        return redirect()
        ->route('tasks.index');   
    }
    public function show($task_id)
    {
        $task   = DB::table('tasks')
                    ->get();
        $subtask = DB::table('subtasks')
                    ->where('task_id', $task_id)
                    ->get();
        $this->get_data($task);
        return  view('tasks.calendar')
                ->with('task', $task)
                ->with('subtask', $subtask);
    }
    function get_data($inf) {
        $session = curl_init(); 
        $timeout = 20;
        curl_setopt($session, CURLOPT_URL, $inf);
        curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($session, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($session, CURLOPT_CONNECTTIMEOUT, $timeout);
        $data = curl_exec($session);
        curl_close($session);
    }
    public function edit($task_id)
    {
        $this->importCsv();
        $task = Task::find($task_id);
        return view('tasks.edit')
               ->with('taskUnderEdit', $task);
    }
    public function update(Request $request, $task_id)
    {
        $this->validate($request, [
                'updatedTaskName' => 'required|min:5|max:255',
            ]);
        $task = Task::find($task_id);
        $data = DB::table("subtasks")
                ->select(DB::raw("SUM(task_status) as sumt"), 
                DB::raw("count(task_status) as countt"))
                ->where('task_id', $task_id)
                ->groupBy(DB::raw("task_id"))
                ->get();    
        $datasum = json_decode($data);
            if ($datasum[0]->sumt == $datasum[0]->countt)
            {
              $task->task_status =1;  
            }else{                
              $task->task_status =0;
            }
        $task->task_hint = $request->updatedTaskName;
        $task->save();
        Session::flash('success', 'Task #' . $task_id 
                . ' has been successfully updated.');
        return  redirect()
                ->route('tasks.index');
    }
    public function destroy($task_id)
    {
        $task = Task::find($task_id);
        $task->delete();
        Session::flash('success', 'Task #' . $task_id .
                    ' has been successfully deleted.');
        return redirect()
        ->route('tasks.index');
    }
    public function csvToArray($filename = '', $delimiter = ',')
    {
        if (!file_exists($filename) || !is_readable($filename))
        {
        return false;
        }
        $header = null;
        $data = array();
        if (($handle = fopen($filename, 'r')) !== false)
        {
            while (($row = fgetcsv($handle, 1000, $delimiter)) !== false)
            {
                if (!$header)
                    $header = $row;
                else
                    $data[] = array_combine($header, $row);
            }
            fclose($handle);
        }
        return $data;
    }
    public function importCsv()
    {
        $file = public_path('file/data.csv');
        $customerArr = $this->csvToArray($file);
        return $customerArr;    
    }

}

finalproject/webapp/resources/views/tasks/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> -- Tasks -- </title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="css/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="css/timeline.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/startmin.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="css/morris.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url('/') }}">Home</a>
        </div>

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <!-- Top Navigation: Left Menu -->
        <ul class="nav navbar-nav navbar-left navbar-top-links">
        </ul>
        <ul class="nav navbar-nav navbar-left navbar-top-links">
            <li><a href="{{ url('/home') }}"><i class="fa fa-refresh" aria-hidden="true"></i> Refresh</a></li>
        </ul>

        <!-- Top Navigation: Right Menu -->
        <ul class="nav navbar-right navbar-top-links">
            <li class="dropdown navbar-inverse">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell fa-fw"></i> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu dropdown-alerts">
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-comment fa-fw"></i> New Comment
                                <span class="pull-right text-muted small"></span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a class="text-center" href="#">            
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> Profile <b class="caret"></b>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li>                            <a href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                                    Logout
                            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
            <li>
            <!-- Authentication Links -->
            @if (Auth::guest())
                <li><a href="{{ route('login') }}">Login</a></li>
                <li><a href="{{ route('register') }}">Register</a></li>
            @else
            <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    {{ Auth::user()->name }}
                    </a>

                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <a href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                                    Logout
                            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
                        </li>
                    </ul>
            </li>
            @endif
            </li>

                    </li>
                </ul>
            </li>
        </ul>

        <!-- Sidebar -->
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">

                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-primary" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                        </div>
                    </li>                          
                    <li>
                        <a href="{{ route('tasks.show', '2') }}" class="active"><i class="fa fa-dashboard fa-fw"></i>Calendar</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-sitemap fa-fw"></i>Information<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{{ route('subtasks.show', '3') }}">History</a>
                            </li>
                            <li>
                                <a href="#">List of information <span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <li>
                                        <a href="{{ route('subtasks.show', '1') }}">All Policies-Procedures
                                        </a>

                                    </li>

                                    <li>
                                        <a href="{{ route('subtasks.show', '2') }}">Users</a>
                                        
                                    </li>
                                    <li>
                                        <a href="{{ route('subtasks.show', '4') }}">Appointments</a>
                                        
                                    </li>
                                      <li>
                                        <a href="{{ route('subtasks.show', '5') }}">Table Request</a>
                                        
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
    <!-- Page Content -->
    <div id="page-wrapper">
        <div class="container-fluid">

            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"></h1>
                    <body>
    {{-- display success message --}}
    @if (Session::has('success'))
      <div class="alert alert-success">
        <strong>Success:</strong> {{ Session::get('success') }}
      </div>
    @endif

    {{-- display error message --}}
    @if (count($errors) > 0)
      <div class="alert alert-danger">
        <strong>Error:</strong>
        <ul>
          @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
    @endif
    <div class="row" style='margin-top: 10px; margin-bottom: 10px;'>
      <form action="{{ route('tasks.store') }}" method='POST'>
      {{ csrf_field() }}
        <div class="col-md-1">
          <input type="submit" class='btn btn-primary btn-block' value='Csv'>
        </div>

      </form>
    </div>

    {{-- display stored tasks --}}
    @if (count($storedTasks) > 0)
    <table id="table" class="table">
<th class="hd">Id</th>
<th class="hd">Description </th>
<th class="hdpcount">Nb of Procedures</th>
</table>
          @foreach ($storedTasks as $storedTask)
             <td>
               <details>
               <table id="table" class="table">
              @foreach($storedTask->subtasks as $subvalue) 
              <form action="{{ route('subtasks.edit', $subvalue['subtask_id']) }}">

              <h3> <tr><td>
              <header class="pdate-detail">{{ $subvalue['subtask_due'] }}</header><br>
              {{ $subvalue['subtask_name'] }}<br>

              <p id="demo">
               {{  $subvalue['task_status'] == 1 ? 'Complete' : 'Incomplete' }}
              </p>
              <a href="{{ route('subtasks.edit', $subvalue['id']) }}">submit</a>
              </td></tr></h3> 
                </form>
                @endforeach
                </table>

                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
            </td> 
            <summary>
                        <header id="p-date" class="p-date"><header class="hd">Start Date
                        </header> 
                        {{ date($storedTask->created_at) }}
                                      <td><a href="{{ route('tasks.edit', ['tasks'=>$storedTask->id]) }}" class='btn btn-default' onclick="setTimeout(myFunction, 0);">
              <th>{{ $storedTask->task_status == 1 ? 'Complete' : 'Incomplete' }}</th>
                  </a>
              </td>
                        </header>
                        <p id="demo2"> </p>
<script>
//var timestamp = 1301090400,
//date = new Date(timestamp * 1000),
var date =  $("#demo3").text();
datevalues = [
   date.getFullYear(),
   date.getMonth()+1,
   date.getfDate(),
   date.getHours(),
   date.getMinutes(),
];
</script>
            <table class="tabletask">
              <th class="txtwd"> {{ $storedTask->id }}</th>
              <td class="txtwd">{{ $storedTask->task_name }}</td>
              <th class="proc-nb">
              {{ count($storedTask->subtasks)  }}</th>
                     <p class="phint">i<span class="span2">{{ $storedTask->task_info }}</span></p>
            </table>
</head>
<body>
            <script>
            $(document).ready(function(){
                $("button").onclick(function(){

              var x = document.getElementById("p-date").innerHTML;
            //var time = new Date(); 
            console.log(x);
            if (1 < 20) {
                document.getElementByClassName("hd").innerHTML = "Good day";
            } 
                $(".table").fadeIn("slow");
                });
            });
            </script>
                          <header class="p-edate"><header class="p-hint">
                          <header class="hd">your Hint 
                          </header>{{ $storedTask->task_hint }}</header>
                          <header class="hd">End Date 
                          </header>{{ $storedTask->task_due }}</header>
                          <td class="txtwd"><header class="hd"></header>
            </summary> 
             <script>
                function myFunction() {
                    alert('Task Complete');
                }
                function check() {
                    var value = document.getElementById("demo").innerHTML;
                    var value2 = document.getElementById("demo").value;
                    //console.log(value);
                    document.getElementById("myCheck").checked = true;
                }
            </script>
              <td>
                  <script type="text/javascript">
                      function showDiv() {
                        document.getElementById('show').style.display = "block";
                       }
                  </script>
              </td>
            </tr>
                  </table>
                        </details>
          @endforeach
    @endif
    <div class="row text-center">
      {{ $storedTasks->links() }}
    </div>

  </div>
</div>
<script src="https://www.gstatic.com/firebasejs/3.8.0/firebase.js"></script>
<script>
  // Initialize Firebase
  var config = {
    apiKey: "AIzaSyCIAOobzR2VMitzrCslmp9ySUfIDPOI_kc",
    authDomain: "task-391b9.firebaseapp.com",
    databaseURL: "https://task-391b9.firebaseio.com",
    projectId: "task-391b9",
    storageBucket: "task-391b9.appspot.com",
    messagingSenderId: "559365832139"
  };
  firebase.initializeApp(config);
</script>
</body>  <!-- ... Your content goes here ... -->
        </div>
    </div>
</div>
<!-- jQuery -->
<script src="js/jquery.min.js"></script>
<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>
<!-- Metis Menu Plugin JavaScript -->
<script src="js/metisMenu.min.js"></script>
<!-- Custom Theme JavaScript -->
<script src="js/startmin.js"></script>
</body>
</html>

finalproject/webapp/resources/views/tasks/calendar.blade.php
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <title>Calendar</title>
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.css"/>
    </head>
            <div class="container">
    <body id="bd">
        <!-- We will attach the calendar to this element -->
              <li>
                <a href="{{ url('/home') }}">Home</a>
              </li>
        <select>
            @foreach ($task as $storedTask)
             <div id="calendar">{{ $storedTask->task_name }}</div>
              @endforeach
         </select>    
             <ul>
            @foreach ($task as $storedTask)
             <li id="calendar"> {{  $storedTask->task_name }}!{{$storedTask->created_at}}!{{ $storedTask->task_due }}!            

            @foreach ($subtask as $sTask)
            {{ $sTask->subtask_name }}
            @endforeach

           ! {{  $storedTask->task_hint }}
             </li>         
              @endforeach
            </ul>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.min.js"></script>
        <script>
            var Variable ;
            var Variable1 ;
            var Variable2 ;
        $('select').change(function() {
        var num = parseInt($(this).val(), 10);
        var container = $('<div />');
             for(var i = 1; i <= num; i++) {
                 container.append('<input id="id'+i+'" name="name'+i+'" />');
             }
             $('somewhere').html(container);
        });
        $.ajax({
        type: 'POST',
        url: 'myfile.php',
        success: function(result) {
            var jsonData = JSON.parse(result);
            // do something with the jsonData
    }
});
        $( "li" ).each(function( index ) {
            var value = [];
            value[index] = $( this ).text();
            var myarr = value[index].split("!");
           // var myJsonString = JSON.stringify(myarr[1]);
            //console.log(myJsonString);
            var jsonArr = [];
            var result = [];
            var valuetitle = [];
            var valuedate = [];
            var evens = [];
            var odds = [];       
                if ((index % 2) != 1) {
                    evens.push(index);                       
                }
                else {
                    odds.push(index);
                }       
      //  for (var i = 0; i < status.options.length; i++) {
        //    }
       // var date = new Date(myarr[1]);
      //var mm =myarr[1].toString('dd-MMM-yyyy');
                    jsonArr.push({
                        "title": myarr[0],
                        "start": myarr[1]
                     });
                    result ='Task:' + myarr[0] 
                    + myarr[3] +'Hint:' + myarr[4];
                    valuetitle.push(myarr[0]);  
                    valuedate.push(myarr[1]);    
            $('#calendar').fullCalendar({

                events: [{"title":result,
                         "start":myarr[1],
                         "end":myarr[2],
                         "rendering": 'background',
                        "allDay": false,
                        "startEditable": true
                          }]
            });
                var myJsonString = JSON.stringify(jsonArr);    
                window.Variable1 = valuetitle;
                window.Variable2 = valuedate;
                window.Variable = JSON.stringify(jsonArr);
            });
            (function ($myJsonString) {

 // for (var i = 0; i < 3; i++) {
// console.log(yourGlobalVariable);
//}      
//$('#calendar').fullCalendar({

//    events: [{"title":yourGlobalVariable1,
//             "start":yourGlobalVariable2
 //           }]
//});
            })(jQuery);
        </script>

    </body>
</div>
</html>

finalproject/webapp/resources/views/tasks/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">

  {{-- bootstrap css CDN --}}
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  {{-- bootstrap js CDN --}}
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <title>Commit the Task</title>
</head>
<body>
<div class="container">
  <div class="col-md-offset-2 col-md-8">
    <div class="row">
      <h1>message</h1>
    </div>

    {{-- display success message --}}
    @if (Session::has('success'))
      <div class="alert alert-success">
        <strong>Success:</strong> {{ Session::get('success') }}
      </div>
    @endif

    {{-- display error message --}}
    @if (count($errors) > 0)
      <div class="alert alert-danger">
        <strong>Error:</strong>
        <ul>
          @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
    @endif

    <div class="row">
      <form action="{{ route('tasks.update', [$taskUnderEdit->id]) }}" method='POST'>
      {{ csrf_field() }}
      <input type="hidden" name='_method' value='PUT'>
        <div class="form-group">
          <p type="text" name='updatedTaskName' class='form-control input-lg' value='{{ $taskUnderEdit->task_info }}'></p>
        </div>

        <div class="form-group">
          <input type="text" name='updatedTaskName' class='form-control input-lg' value='{{ $taskUnderEdit->task_hint }}'>
        </div>

        <div class="form-group">
          <input type="submit" value='Save Changes' class='btn btn-success btn-lg'>
          <a href="" class='btn btn-danger btn-lg pull-right'>Go Back</a>
        </div>
      </form>
    </div>

 
  </div>
</div>


</body>
</html>

finalproject/webapp/resources/views/tasks/old.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="UTF-8">

  {{-- bootstrap css CDN --}}
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  {{-- bootstrap js CDN --}}
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <title>Todo List App</title>
</head>
<body>
<div class="container">
  <div class="col-md-offset-2 col-md-8">
    <div class="row">
      <h1>Todo List</h1>
    </div>

    {{-- display success message --}}
    @if (Session::has('success'))
      <div class="alert alert-success">
        <strong>Success:</strong> {{ Session::get('success') }}
      </div>
    @endif

    {{-- display error message --}}
    @if (count($errors) > 0)
      <div class="alert alert-danger">
        <strong>Error:</strong>
        <ul>
          @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
    @endif

    <div class="row" style='margin-top: 10px; margin-bottom: 10px;'>
      <form action="{{ route('tasks.store') }}" method='POST'>
      {{ csrf_field() }}

        <div class="col-md-9">
          <input type="text" name='newTaskName' class='form-control'>
        </div>

        <div class="col-md-3">
          <input type="submit" class='btn btn-primary btn-block' value='Add Task'>
        </div>
      </form>
    </div>

    {{-- display stored tasks --}}
    @if (count($storedTasks) > 0)
      <table class="table">
        <thead>
          <th>Task #</th>
          <th>Name</th>
          <th>Edit</th>
          <th>Delete</th>
        </thead>

        <tbody>
          @foreach ($storedTasks as $storedTask)
            <tr>
              <th>{{ $storedTask->task_id }}</th>
              <td>{{ $storedTask->task_name }}</td>
              <td><a href="{{ route('tasks.update', ['tasks'=>$storedTask->task_id]) }}" class='btn btn-default'>Finish !</a></td>
              <td>
                <form action="{{ route('tasks.destroy', ['tasks'=>$storedTask->id]) }}" method='POST'>
                  {{ csrf_field() }}
                  <input type="hidden" name='_method' value='DELETE'>

                  <input type="submit" class='btn btn-danger' value='Delete'>
                </form>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
    @endif

    <div class="row text-center">
      {{ $storedTasks->links() }}
    </div>

  </div>
</div>
</body>
</html>